load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "attributes",
    hdrs = ["public/tr_utils/type_attributes.h"],
    includes = ["public"],
    visibility = ["//visibility:public"],
)
